/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Managers.BattingModel;
import Managers.DatabaseManager;
import Managers.LessonModel;
import Managers.TeacherModel;
import com.formdev.flatlaf.ui.FlatButtonBorder;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;

/**
 *
 * @author janch
 */
public class MainScreen extends javax.swing.JFrame
{
    Color baseBlue = new Color(0, 0, 51),
            lightBlue = new Color(0,51,102);
    /**
     * Creates new form MainScreen
     */
    public MainScreen()
    {
        try
        {
            DatabaseManager.init();
            battingModel = new BattingModel();
            teacherModel = new TeacherModel();
        } catch (SQLException ex)
        {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPanel = new javax.swing.JPanel();
        battingButtonPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        statisticsButtonPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        teacherButtonPane1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hideSidePanelButton = new javax.swing.JButton();
        mainViewPanel = new javax.swing.JPanel();
        battingViewPanel = new javax.swing.JPanel();
        battingBodyPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        battingTable = new javax.swing.JTable();
        battingTopMainPanel = new javax.swing.JPanel();
        sendTableButton = new javax.swing.JButton();
        absenteesViewPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        battingHeaderPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        showSidePanelButton = new javax.swing.JButton();
        teacherViewPanel = new javax.swing.JPanel();
        teacherHeaderPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        showSidePanelButton1 = new javax.swing.JButton();
        teacherBodyPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        contactDetailsPanel = new javax.swing.JPanel();
        emailContactLabel = new javax.swing.JLabel();
        phoneNumberContactLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addTeachersThroughCSVButton = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        teacherBulkInfoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTree = new javax.swing.JTree();
        jScrollPane30 = new javax.swing.JScrollPane();
        tblViewTimeTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        teachersList = new javax.swing.JList<>();
        statisticsViewPanel = new javax.swing.JPanel();
        statisticsHeaderPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        showSidePanelButton2 = new javax.swing.JButton();
        statisticsBodyPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuPanel.setBackground(new java.awt.Color(0, 0, 51));

        battingButtonPane.setBackground(new java.awt.Color(0, 0, 51));
        battingButtonPane.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                battingButtonPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                battingButtonPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                battingButtonPaneMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Batting");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout battingButtonPaneLayout = new javax.swing.GroupLayout(battingButtonPane);
        battingButtonPane.setLayout(battingButtonPaneLayout);
        battingButtonPaneLayout.setHorizontalGroup(
            battingButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingButtonPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );
        battingButtonPaneLayout.setVerticalGroup(
            battingButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        statisticsButtonPane.setBackground(new java.awt.Color(0, 0, 51));
        statisticsButtonPane.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                statisticsButtonPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                statisticsButtonPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                statisticsButtonPaneMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Statistics");

        javax.swing.GroupLayout statisticsButtonPaneLayout = new javax.swing.GroupLayout(statisticsButtonPane);
        statisticsButtonPane.setLayout(statisticsButtonPaneLayout);
        statisticsButtonPaneLayout.setHorizontalGroup(
            statisticsButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsButtonPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        statisticsButtonPaneLayout.setVerticalGroup(
            statisticsButtonPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        teacherButtonPane1.setBackground(new java.awt.Color(0, 0, 51));
        teacherButtonPane1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                teacherButtonPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                teacherButtonPane1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                teacherButtonPane1MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Teacher");

        javax.swing.GroupLayout teacherButtonPane1Layout = new javax.swing.GroupLayout(teacherButtonPane1);
        teacherButtonPane1.setLayout(teacherButtonPane1Layout);
        teacherButtonPane1Layout.setHorizontalGroup(
            teacherButtonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherButtonPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );
        teacherButtonPane1Layout.setVerticalGroup(
            teacherButtonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        hideSidePanelButton.setBackground(menuPanel.getBackground());
        hideSidePanelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hideSidePanelButton.setForeground(new java.awt.Color(166, 142, 60));
        hideSidePanelButton.setText("<<");
        hideSidePanelButton.setBorder(null);
        hideSidePanelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideSidePanelButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                hideSidePanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                hideSidePanelButtonMouseExited(evt);
            }
        });
        hideSidePanelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                hideSidePanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(battingButtonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teacherButtonPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statisticsButtonPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hideSidePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(hideSidePanelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(battingButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(teacherButtonPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statisticsButtonPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainViewPanel.setLayout(new java.awt.CardLayout());

        battingViewPanel.setBackground(new java.awt.Color(255, 255, 255));

        battingBodyPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\janch\\OneDrive\\Pictures\\Reddam-house-logo.jpg.jpeg")); // NOI18N

        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        battingTable.setBackground(new java.awt.Color(255, 255, 255));
        battingTable.setForeground(new java.awt.Color(51, 51, 51));
        battingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Days", "L1", "L2", "L3", "L4", "L5", "Title 7", "L7", "L8", "L9", "L10", "L11", "L12", "L13", "L14"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        battingTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        battingTable.setGridColor(new java.awt.Color(204, 204, 204));
        battingTable.setRowHeight(60);
        battingTable.setShowGrid(true);
        jScrollPane2.setViewportView(battingTable);

        battingTopMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sendTableButton.setBackground(new java.awt.Color(166, 142, 60));
        sendTableButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendTableButton.setForeground(new java.awt.Color(255, 255, 255));
        sendTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Send_Icon.png"))); // NOI18N
        sendTableButton.setText("Send");
        sendTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        FlatLineBorder flBorder = new FlatLineBorder(sendTableButton.getInsets(), sendTableButton.getBackground());
        sendTableButton.setBorder(flBorder);
        sendTableButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sendTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout battingTopMainPanelLayout = new javax.swing.GroupLayout(battingTopMainPanel);
        battingTopMainPanel.setLayout(battingTopMainPanelLayout);
        battingTopMainPanelLayout.setHorizontalGroup(
            battingTopMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingTopMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendTableButton)
                .addContainerGap())
        );
        battingTopMainPanelLayout.setVerticalGroup(
            battingTopMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battingTopMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendTableButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        absenteesViewPanel.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("search teacher");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout absenteesViewPanelLayout = new javax.swing.GroupLayout(absenteesViewPanel);
        absenteesViewPanel.setLayout(absenteesViewPanelLayout);
        absenteesViewPanelLayout.setHorizontalGroup(
            absenteesViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absenteesViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        absenteesViewPanelLayout.setVerticalGroup(
            absenteesViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absenteesViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout battingBodyPanel1Layout = new javax.swing.GroupLayout(battingBodyPanel1);
        battingBodyPanel1.setLayout(battingBodyPanel1Layout);
        battingBodyPanel1Layout.setHorizontalGroup(
            battingBodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingBodyPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(battingBodyPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(battingBodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingBodyPanel1Layout.createSequentialGroup()
                        .addGap(951, 951, 951)
                        .addComponent(battingTopMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingBodyPanel1Layout.createSequentialGroup()
                        .addGroup(battingBodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(absenteesViewPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(71, 71, 71))))
        );
        battingBodyPanel1Layout.setVerticalGroup(
            battingBodyPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battingBodyPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(battingTopMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(absenteesViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        battingHeaderPanel.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Batting");

        showSidePanelButton.setBackground(menuPanel.getBackground());
        showSidePanelButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showSidePanelButton.setForeground(new java.awt.Color(166, 142, 60));
        showSidePanelButton.setText(">>");
        showSidePanelButton.setBorder(null);
        showSidePanelButton.setVisible(false);
        showSidePanelButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                showSidePanelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                showSidePanelButtonMouseExited(evt);
            }
        });
        showSidePanelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                showSidePanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout battingHeaderPanelLayout = new javax.swing.GroupLayout(battingHeaderPanel);
        battingHeaderPanel.setLayout(battingHeaderPanelLayout);
        battingHeaderPanelLayout.setHorizontalGroup(
            battingHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battingHeaderPanelLayout.createSequentialGroup()
                .addComponent(showSidePanelButton)
                .addGap(268, 268, 268)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(294, 294, 294))
        );
        battingHeaderPanelLayout.setVerticalGroup(
            battingHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(battingHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addComponent(showSidePanelButton))
        );

        javax.swing.GroupLayout battingViewPanelLayout = new javax.swing.GroupLayout(battingViewPanel);
        battingViewPanel.setLayout(battingViewPanelLayout);
        battingViewPanelLayout.setHorizontalGroup(
            battingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(battingHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(battingBodyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        battingViewPanelLayout.setVerticalGroup(
            battingViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, battingViewPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(battingHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(battingBodyPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainViewPanel.add(battingViewPanel, "card2");

        teacherViewPanel.setBackground(new java.awt.Color(255, 255, 255));

        teacherHeaderPanel.setBackground(new java.awt.Color(0, 0, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Teacher");

        showSidePanelButton1.setBackground(menuPanel.getBackground());
        showSidePanelButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showSidePanelButton1.setForeground(new java.awt.Color(166, 142, 60));
        showSidePanelButton1.setText(">>");
        showSidePanelButton1.setBorder(null);
        showSidePanelButton1.setVisible(false);
        showSidePanelButton1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                showSidePanelButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                showSidePanelButton1MouseExited(evt);
            }
        });
        showSidePanelButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                showSidePanelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherHeaderPanelLayout = new javax.swing.GroupLayout(teacherHeaderPanel);
        teacherHeaderPanel.setLayout(teacherHeaderPanelLayout);
        teacherHeaderPanelLayout.setHorizontalGroup(
            teacherHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherHeaderPanelLayout.createSequentialGroup()
                .addComponent(showSidePanelButton1)
                .addGap(272, 272, 272)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(290, 290, 290))
        );
        teacherHeaderPanelLayout.setVerticalGroup(
            teacherHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addComponent(showSidePanelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        teacherBodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\janch\\OneDrive\\Pictures\\Reddam-house-logo.jpg.jpeg")); // NOI18N

        contactDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));

        emailContactLabel.setText("email@example.com");

        phoneNumberContactLabel.setText("060 000 0000");

        jLabel10.setText("BattingLevel: 12.45");

        addTeachersThroughCSVButton.setText("Insert teachers through csv");

        javax.swing.GroupLayout contactDetailsPanelLayout = new javax.swing.GroupLayout(contactDetailsPanel);
        contactDetailsPanel.setLayout(contactDetailsPanelLayout);
        contactDetailsPanelLayout.setHorizontalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addComponent(emailContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(phoneNumberContactLabel)
                .addGap(75, 75, 75)
                .addComponent(jLabel10)
                .addGap(117, 117, 117)
                .addComponent(addTeachersThroughCSVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contactDetailsPanelLayout.setVerticalGroup(
            contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailContactLabel)
                    .addComponent(phoneNumberContactLabel)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contactDetailsPanelLayout.createSequentialGroup()
                .addComponent(addTeachersThroughCSVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        teacherBulkInfoPanel.setBackground(new java.awt.Color(255, 255, 255));

        teacherTree.setBackground(new java.awt.Color(255, 255, 255));
        teacherTree.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        teacherTree.setForeground(new java.awt.Color(0, 0, 51));
        teacherTree.setModel(teacherModel);
        jScrollPane1.setViewportView(teacherTree);

        tblViewTimeTable.setBackground(new java.awt.Color(255, 255, 255));
        tblViewTimeTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblViewTimeTable.setForeground(new java.awt.Color(102, 102, 102));
        tblViewTimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"Monday", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Tuesday", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Wednesday", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Thursday", null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Friday", null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Day", "L1", "L2", "L3", "L4", "L5", "L6", "L7", "L8", "L9", "L10", "L11", "L12", "L13", "L14"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblViewTimeTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        tblViewTimeTable.setCellSelectionEnabled(true);
        tblViewTimeTable.setEnabled(false);
        tblViewTimeTable.setGridColor(new java.awt.Color(51, 51, 51));
        tblViewTimeTable.setOpaque(false);
        tblViewTimeTable.setRowHeight(60);
        tblViewTimeTable.setRowMargin(1);
        tblViewTimeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblViewTimeTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblViewTimeTable.setShowGrid(true);
        tblViewTimeTable.setSurrendersFocusOnKeystroke(true);
        // tblViewTimeTable.setRowHeight(tblViewTimeTable.getHeight() / 5 +1);
        //System.out.println(tblViewTimeTable.getModel().getHeight() + "");
        tblViewTimeTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tblViewTimeTableMouseClicked(evt);
            }
        });
        jScrollPane30.setViewportView(tblViewTimeTable);

        javax.swing.GroupLayout teacherBulkInfoPanelLayout = new javax.swing.GroupLayout(teacherBulkInfoPanel);
        teacherBulkInfoPanel.setLayout(teacherBulkInfoPanelLayout);
        teacherBulkInfoPanelLayout.setHorizontalGroup(
            teacherBulkInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherBulkInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(teacherBulkInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teacherBulkInfoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane30)
                    .addContainerGap()))
        );
        teacherBulkInfoPanelLayout.setVerticalGroup(
            teacherBulkInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherBulkInfoPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(teacherBulkInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(teacherBulkInfoPanelLayout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        teachersList.setBackground(new java.awt.Color(255, 255, 255));
        teachersList.setModel(new DefaultListModel<String>());
        teachersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        teachersList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                teachersListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(teachersList);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherBulkInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherBulkInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teacherBodyPanelLayout = new javax.swing.GroupLayout(teacherBodyPanel);
        teacherBodyPanel.setLayout(teacherBodyPanelLayout);
        teacherBodyPanelLayout.setHorizontalGroup(
            teacherBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherBodyPanelLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(contactDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherBodyPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(teacherBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherBodyPanelLayout.createSequentialGroup()
                        .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        teacherBodyPanelLayout.setVerticalGroup(
            teacherBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contactDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        javax.swing.GroupLayout teacherViewPanelLayout = new javax.swing.GroupLayout(teacherViewPanel);
        teacherViewPanel.setLayout(teacherViewPanelLayout);
        teacherViewPanelLayout.setHorizontalGroup(
            teacherViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacherHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teacherBodyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        teacherViewPanelLayout.setVerticalGroup(
            teacherViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherViewPanelLayout.createSequentialGroup()
                .addComponent(teacherHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(teacherBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        mainViewPanel.add(teacherViewPanel, "card3");

        statisticsViewPanel.setBackground(new java.awt.Color(255, 255, 255));

        statisticsHeaderPanel.setBackground(new java.awt.Color(0, 0, 51));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Statistics");

        showSidePanelButton2.setBackground(menuPanel.getBackground());
        showSidePanelButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        showSidePanelButton2.setForeground(new java.awt.Color(166, 142, 60));
        showSidePanelButton2.setText(">>");
        showSidePanelButton2.setBorder(null);
        showSidePanelButton2.setVisible(false);
        showSidePanelButton2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                showSidePanelButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                showSidePanelButton2MouseExited(evt);
            }
        });
        showSidePanelButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                showSidePanelButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statisticsHeaderPanelLayout = new javax.swing.GroupLayout(statisticsHeaderPanel);
        statisticsHeaderPanel.setLayout(statisticsHeaderPanelLayout);
        statisticsHeaderPanelLayout.setHorizontalGroup(
            statisticsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsHeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showSidePanelButton2)
                .addGap(259, 259, 259)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(297, 297, 297))
        );
        statisticsHeaderPanelLayout.setVerticalGroup(
            statisticsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsHeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addComponent(showSidePanelButton2))
        );

        statisticsBodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\janch\\OneDrive\\Pictures\\Reddam-house-logo.jpg.jpeg")); // NOI18N

        javax.swing.GroupLayout statisticsBodyPanelLayout = new javax.swing.GroupLayout(statisticsBodyPanel);
        statisticsBodyPanel.setLayout(statisticsBodyPanelLayout);
        statisticsBodyPanelLayout.setHorizontalGroup(
            statisticsBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticsBodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        statisticsBodyPanelLayout.setVerticalGroup(
            statisticsBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statisticsBodyPanelLayout.createSequentialGroup()
                .addGap(0, 537, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        javax.swing.GroupLayout statisticsViewPanelLayout = new javax.swing.GroupLayout(statisticsViewPanel);
        statisticsViewPanel.setLayout(statisticsViewPanelLayout);
        statisticsViewPanelLayout.setHorizontalGroup(
            statisticsViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticsHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(statisticsBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        statisticsViewPanelLayout.setVerticalGroup(
            statisticsViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsViewPanelLayout.createSequentialGroup()
                .addComponent(statisticsHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statisticsBodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainViewPanel.add(statisticsViewPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainViewPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battingButtonPaneMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_battingButtonPaneMouseEntered
    {//GEN-HEADEREND:event_battingButtonPaneMouseEntered
        // TODO add your handling code here:
        lightenBackColour(battingButtonPane);
    }//GEN-LAST:event_battingButtonPaneMouseEntered

    private void battingButtonPaneMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_battingButtonPaneMouseExited
    {//GEN-HEADEREND:event_battingButtonPaneMouseExited
        // TODO add your handling code here:
        resetBackColour(battingButtonPane);
    }//GEN-LAST:event_battingButtonPaneMouseExited

    private void teacherButtonPane1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_teacherButtonPane1MouseEntered
    {//GEN-HEADEREND:event_teacherButtonPane1MouseEntered
        // TODO add your handling code here:
        lightenBackColour(teacherButtonPane1);
    }//GEN-LAST:event_teacherButtonPane1MouseEntered

    private void teacherButtonPane1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_teacherButtonPane1MouseExited
    {//GEN-HEADEREND:event_teacherButtonPane1MouseExited
        // TODO add your handling code here:
        resetBackColour(teacherButtonPane1);
    }//GEN-LAST:event_teacherButtonPane1MouseExited

    private void statisticsButtonPaneMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_statisticsButtonPaneMouseEntered
    {//GEN-HEADEREND:event_statisticsButtonPaneMouseEntered
        // TODO add your handling code here:
        lightenBackColour(statisticsButtonPane);
    }//GEN-LAST:event_statisticsButtonPaneMouseEntered

    private void statisticsButtonPaneMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_statisticsButtonPaneMouseExited
    {//GEN-HEADEREND:event_statisticsButtonPaneMouseExited
        // TODO add your handling code here:
        resetBackColour(statisticsButtonPane);
    }//GEN-LAST:event_statisticsButtonPaneMouseExited

    private void battingButtonPaneMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_battingButtonPaneMouseClicked
    {//GEN-HEADEREND:event_battingButtonPaneMouseClicked
        // TODO add your handling code here:
        battingViewPanel.setVisible(true);
        teacherViewPanel.setVisible(false);
        statisticsViewPanel.setVisible(false);
    }//GEN-LAST:event_battingButtonPaneMouseClicked

    private void teacherButtonPane1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_teacherButtonPane1MouseClicked
    {//GEN-HEADEREND:event_teacherButtonPane1MouseClicked
        // TODO add your handling code here:
        battingViewPanel.setVisible(false);
        teacherViewPanel.setVisible(true);
        statisticsViewPanel.setVisible(false);
    }//GEN-LAST:event_teacherButtonPane1MouseClicked

    private void statisticsButtonPaneMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_statisticsButtonPaneMouseClicked
    {//GEN-HEADEREND:event_statisticsButtonPaneMouseClicked
        // TODO add your handling code here:
        battingViewPanel.setVisible(false);
        teacherViewPanel.setVisible(false);
        statisticsViewPanel.setVisible(true);
    }//GEN-LAST:event_statisticsButtonPaneMouseClicked

    private void hideSidePanelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hideSidePanelButtonActionPerformed
    {//GEN-HEADEREND:event_hideSidePanelButtonActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(false);
        
        if (battingViewPanel.isVisible()) showSidePanelButton.setVisible(true);
        else if (teacherViewPanel.isVisible()) showSidePanelButton1.setVisible(true);
        else showSidePanelButton2.setVisible(true);
    }//GEN-LAST:event_hideSidePanelButtonActionPerformed

    private void showSidePanelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showSidePanelButtonActionPerformed
    {//GEN-HEADEREND:event_showSidePanelButtonActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(true);
        showSidePanelButton.setVisible(false);
    }//GEN-LAST:event_showSidePanelButtonActionPerformed

    private void showSidePanelButtonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButtonMouseEntered
    {//GEN-HEADEREND:event_showSidePanelButtonMouseEntered
        // TODO add your handling code here:
        lightenBackColour(showSidePanelButton);
    }//GEN-LAST:event_showSidePanelButtonMouseEntered

    private void showSidePanelButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButtonMouseExited
    {//GEN-HEADEREND:event_showSidePanelButtonMouseExited
        // TODO add your handling code here:
        resetBackColour(showSidePanelButton);
    }//GEN-LAST:event_showSidePanelButtonMouseExited

    private void hideSidePanelButtonMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hideSidePanelButtonMouseEntered
    {//GEN-HEADEREND:event_hideSidePanelButtonMouseEntered
        // TODO add your handling code here:
        lightenBackColour(hideSidePanelButton);
    }//GEN-LAST:event_hideSidePanelButtonMouseEntered

    private void hideSidePanelButtonMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_hideSidePanelButtonMouseExited
    {//GEN-HEADEREND:event_hideSidePanelButtonMouseExited
        // TODO add your handling code here:
        resetBackColour(hideSidePanelButton);
    }//GEN-LAST:event_hideSidePanelButtonMouseExited

    private void showSidePanelButton1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButton1MouseEntered
    {//GEN-HEADEREND:event_showSidePanelButton1MouseEntered
        // TODO add your handling code here:
        lightenBackColour(showSidePanelButton1);
    }//GEN-LAST:event_showSidePanelButton1MouseEntered

    private void showSidePanelButton1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButton1MouseExited
    {//GEN-HEADEREND:event_showSidePanelButton1MouseExited
        // TODO add your handling code here:
        resetBackColour(showSidePanelButton1);
    }//GEN-LAST:event_showSidePanelButton1MouseExited

    private void showSidePanelButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showSidePanelButton1ActionPerformed
    {//GEN-HEADEREND:event_showSidePanelButton1ActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(true);
        showSidePanelButton1.setVisible(false);
    }//GEN-LAST:event_showSidePanelButton1ActionPerformed

    private void showSidePanelButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_showSidePanelButton2ActionPerformed
    {//GEN-HEADEREND:event_showSidePanelButton2ActionPerformed
        // TODO add your handling code here:
        menuPanel.setVisible(true);
        showSidePanelButton2.setVisible(false);
    }//GEN-LAST:event_showSidePanelButton2ActionPerformed

    private void showSidePanelButton2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButton2MouseEntered
    {//GEN-HEADEREND:event_showSidePanelButton2MouseEntered
        // TODO add your handling code here:
        lightenBackColour(showSidePanelButton2);
    }//GEN-LAST:event_showSidePanelButton2MouseEntered

    private void showSidePanelButton2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_showSidePanelButton2MouseExited
    {//GEN-HEADEREND:event_showSidePanelButton2MouseExited
        // TODO add your handling code here:
        resetBackColour(showSidePanelButton2);
    }//GEN-LAST:event_showSidePanelButton2MouseExited

    private void sendTableButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sendTableButtonActionPerformed
    {//GEN-HEADEREND:event_sendTableButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendTableButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblViewTimeTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblViewTimeTableMouseClicked
    {//GEN-HEADEREND:event_tblViewTimeTableMouseClicked
        // TODO add your handling code here:
//        if (tblViewTimeTable.isEnabled())
//        {
//            int row = tblViewTimeTable.getSelectedRow(), col = tblViewTimeTable.getSelectedColumn();
//
//            Cell selectedC = new Cell(row, col - 1);
//
//            changeTeacher_tableSelection[row][col - 1] = !changeTeacher_tableSelection[row][col - 1];
//            if (tblViewTimeTable.getValueAt(row, col) == null)
//            {
//                change_selectedCells.add(selectedC);
//                tblViewTimeTable.setValueAt("X", row, col);
//            } else
//            {
//                tblViewTimeTable.setValueAt("", row, col);
//            }
//        }
    }//GEN-LAST:event_tblViewTimeTableMouseClicked

    private void teachersListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_teachersListMouseClicked
    {//GEN-HEADEREND:event_teachersListMouseClicked
        // TODO add your handling code here:
        teacherModel.setSelectedTeacherIndex(teachersList.getSelectedIndex());
        teacherTree.setModel(teacherModel);
        //populateTeacherTree();
    }//GEN-LAST:event_teachersListMouseClicked

    private void lightenBackColour(JComponent c)
    {
        c.setBackground(lightBlue);
    }
    private void resetBackColour(JComponent c)
    {
        c.setBackground(baseBlue);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
                javax.swing.UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
//            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainScreen().setVisible(true);
            }
        });
    }
    
    private LessonModel lessonModel;
    private BattingModel battingModel;
    private TeacherModel teacherModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel absenteesViewPanel;
    private javax.swing.JButton addTeachersThroughCSVButton;
    private javax.swing.JPanel battingBodyPanel1;
    private javax.swing.JPanel battingButtonPane;
    private javax.swing.JPanel battingHeaderPanel;
    private javax.swing.JTable battingTable;
    private javax.swing.JPanel battingTopMainPanel;
    private javax.swing.JPanel battingViewPanel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel contactDetailsPanel;
    private javax.swing.JLabel emailContactLabel;
    private javax.swing.JButton hideSidePanelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel mainViewPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel phoneNumberContactLabel;
    private javax.swing.JButton sendTableButton;
    private javax.swing.JButton showSidePanelButton;
    private javax.swing.JButton showSidePanelButton1;
    private javax.swing.JButton showSidePanelButton2;
    private javax.swing.JPanel statisticsBodyPanel;
    private javax.swing.JPanel statisticsButtonPane;
    private javax.swing.JPanel statisticsHeaderPanel;
    private javax.swing.JPanel statisticsViewPanel;
    private javax.swing.JTable tblViewTimeTable;
    private javax.swing.JPanel teacherBodyPanel;
    private javax.swing.JPanel teacherBulkInfoPanel;
    private javax.swing.JPanel teacherButtonPane1;
    private javax.swing.JPanel teacherHeaderPanel;
    private javax.swing.JTree teacherTree;
    private javax.swing.JPanel teacherViewPanel;
    private javax.swing.JList<String> teachersList;
    // End of variables declaration//GEN-END:variables

    private void populateTeacherTree()
    {
        
    }
}
