/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testing;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;



/**
 *
 * @author janch
 */
public class TransformTable_PNG_PDF extends javax.swing.JFrame
{

    /**
     * Creates new form TransformTable_PNG_PDF
     */
    public TransformTable_PNG_PDF()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PrintTableButton = new javax.swing.JButton();
        emailButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {"P1", null, null, null, null, "p2", "p6", null, null, "p8", "p9", "p10", null, null},
                {"p2", "p2", null, null, null, null, null, "p10", null, null, "p1", "p2", null, "p4"},
                {null, "p3", "p5", null, "p4", "p4", "p6", "p6", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, "p8", "p9", "p10", "p9", "p11"}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PrintTableButton.setText("Print Out");
        PrintTableButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PrintTableButtonActionPerformed(evt);
            }
        });

        emailButton.setText("Email");
        emailButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                emailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrintTableButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrintTableButton)
                    .addComponent(emailButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintTableButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PrintTableButtonActionPerformed
    {//GEN-HEADEREND:event_PrintTableButtonActionPerformed
       /*
        1. Create a PDF document using the Document class.
        2. Create a PdfWriter object using the PdfWriter.getInstance() method and pass the document and a FileOutputStream object as arguments.
        3. Open the document using the open() method.
        4. Create a PdfPTable object and add the column headers to it.
        5. Iterate through the rows of the JTable and add each row to the PdfPTable object.
        6. Add the PdfPTable object to the document using the add() method.
        7. Close the document using the close() method.
       */
        try
        {
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream("data\\table"+ LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy H-m-s")) +".pdf"));
            doc.open();
            
            int nrCols = jTable1.getColumnCount();
            PdfPTable pdfTable = new PdfPTable(nrCols);
            
            for (int i = 0; i < nrCols; i++)
            {
                pdfTable.addCell(jTable1.getColumnName(i));
            }
            for (int row = 0; row < jTable1.getRowCount(); row ++)
            {
                for (int col = 0; col < nrCols; col++)
                {
                    pdfTable.addCell((String) jTable1.getValueAt(row, col));
                }
            }
            doc.add(pdfTable);
            doc.close();
            
        }catch (DocumentException ex) 
        {
            ex.printStackTrace();
        }catch (FileNotFoundException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PrintTableButtonActionPerformed

    private void emailButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_emailButtonActionPerformed
    {//GEN-HEADEREND:event_emailButtonActionPerformed
        // TODO add your handling code here:
        Email_JavaMail emailer = new Email_JavaMail();
        PrintTableButtonActionPerformed(evt);
        
        emailer.mailAttachment("janchristiaan.jacobs@reddam.house", "janchristiaan.jacobs@gmail.com", "Sending an email with a pdf file", "Text", "data/table.pdf");
    }//GEN-LAST:event_emailButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TransformTable_PNG_PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TransformTable_PNG_PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TransformTable_PNG_PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TransformTable_PNG_PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TransformTable_PNG_PDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrintTableButton;
    private javax.swing.JButton emailButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
